
export const loginStyles = {
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#fff',
    paddingTop: 100,
  },
  headerWrapper: {
    width: '100%',
  },
  logo: {
    color: '#008751',
    textAlign: 'center',
    fontSize: 30,
    fontWeight: 'bold',
  },
  loginText: {
    textAlign: 'left',
    marginTop: 40,
    fontFamily: 'Montserrat',
  },
  formWrapper: {
    marginTop: 20,
  },
  input: {
    width: '100%',
    borderRadius: 5,
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    paddingHorizontal: 10,
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    backgroundColor: '#fff',
    borderEndColor: 'transparent',
    borderBottomColor: 'transparent',
    borderTopColor: 'transparent',
    borderLeftColor: 'transparent',
    pointerEvents: 'auto',
    marginBottom: 12,
  },
  loginButton: {
    backgroundColor: '#008751',
    color: '#fff',
    paddingVertical: 15,
    width: '100%',
    borderRadius: 5,
  },
  loginButtonText: {
    textAlign: 'center',
    color: '#fff',
  },
  otherSignIn: {
    marginTop: 50,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  siginInWithOtherText: {
    textAlign: 'center',
  },
  iconWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginTop: 20,
  },
  icon: {
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 5,
  },
  forgotPasswordText: {
    marginTop: 12,
    color: '#008751',
    textAlign: 'right',
  },
  signUpTextWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  signUpText: {
    color: '#008751',
  },
  errorText: {
    color: 'red',
    marginBottom: 12,
    textAlign: 'center',
  },
}